--model_name_or_path
bert-base-multilingual-cased
--train_file
../data/kftt/kftt_dev.json
--test_file
../data/kftt/kftt_devtest.json
--version_2_with_negative
--per_device_train_batch_size
12
--learning_rate
3e-5
--num_train_epochs
2
--max_seq_length
384
--doc_stride
128
--output_dir
../out/